npcs:

  '0': "Орк"
  '1': "Чел"
  '2': "Дварф"
  '3': "Эльф"
  '14': "Глава Совета"
  '15': "СтражникХ"
  '18': "bebra"
  '20': "skul"
  '24': "gob"
  '29': "бармен"
  '30': "test"
  '41': "test2"
  '42': "торговец А"
  '44': "God Adventure"
  
hide_npcs:
  18: '!npc_hide'
  20: '!npc_hide'
  
player_hider:
  target_player: 
  
  
  
menus:
  questMenu:
    height: 4
    title: "&6&lQuests"
    bind: "openMenuItem"
    command: "/daily"
    slots:
      0-3: "filler,filler,filler,filler"
      4: "reputation"
      5-8: "filler,filler,filler,filler"
      9: "skeletonQuestActive,skeletonQuestDone"
      10: "goldQuestActive,goldQuestDone"
      27-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"

    items:
      skeletonQuestActive:
        item: "skeletonQuestActiveItem"
        amount: 1
        conditions: "!skeletonQuestDone"
        text:
            - "&7[Quest] &f&lBone ripper"
            - "&f&oRipp some skeletons off"
            - "&f&otheir bones to complete"
            - "&f&othis quest."
            - "&f&o"
            - "&eLeft click to locate NPC."
        click:
          left: "locationNotify"
        close: true
      skeletonQuestDone:
        item: "questDone"
        amount: 1
        conditions: "skeletonQuestDone"
        text:
            - "&2[Quest] &f&lBone ripper"
            - "&f&oRipp some skeletons off"
            - "&f&otheir bones to complete"
            - "&f&othis quest."
            - "&f&o"
            - "&2Quest completed!"
        close: false
      goldQuestActive:
        item: "goldQuestActiveItem"
        amount: 1
        conditions: "!goldQuestDone"
        text:
            - "&7[Quest] &f&lGold rush"
            - "&f&oMine some gold"
            - "&f&oto complete this quest."
        click:
          left: "locationNotify"
        close: true
      goldQuestDone:
        item: "questDone"
        amount: 1
        conditions: "goldQuestDone"
        text:
            - "&2[Quest] &f&lGold rush"
            - "&f&oMine some gold"
            - "&f&oto complete this quest."
            - "&2Quest completed!"
        close: false
      reputation:
        item: "xpBottle" 
        amount: 1
        text:
            - "&2Quest Level: &6&l%point.quest_reputation.amount%"
        close: true
      filler: 
        text: "&a "
        item: "filler"